version: "3.9"

services:
  book-service:
    build: ./book-service
    ports:
      - "8000:8000"
    volumes:
      - ./book-service:/app
    networks: [ backend ]

  loan-service:
    build: ./loan-service
    ports:
      - "8001:8001"
    volumes:
      - ./loan-service:/app
    networks: [ backend ]

  stat-service:
    build: ./stat-service
    ports:
      - "8002:8002"
    volumes:
      - ./stat-service:/app
    networks: [ backend ]

  user-service:
    build: ./user-service
    ports:
      - "8003:8003"
    volumes:
      - ./user-service:/app
    networks: [ backend ]

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - book-service
      - loan-service
      - stat-service
      - user-service
    networks: [ backend ]

networks:
  backend:
